export const EMPRESA_SELECTED = 'EMPRESA_SELECTED';

export const INPUT_EMPRESA_CHANGED = 'INPUT_EMPRESA_CHANGED';

export const INPUT_PERIODO_CHANGED = 'INPUT_PERIODO_CHANGED';

export const AGREGAR_PERIODO = 'AGREGAR_PERIODO';

export const INPUT_ANIO_CHANGED = 'INPUT_AÑO_CHANGED';

export const CLEAR_PERIODOS_POR_AGREGAR = 'CLEAR_PERIODOS_POR_AGREGAR';

export const CLEAR_INPUTS = 'CLEAR_INPUTS';

export const ADD_DATA_TO_EXPRESSION = 'ADD_DATA_TO_EXPRESSION';

export const TOGGLE_SUCCESSFUL_MESSAGE = 'TOGGLE_SUCCESSFUL_MESSAGE';
