export const INITIAL_DATA_REQUEST = 'INITIAL_DATA_REQUEST';
export const INITIAL_DATA_SUCCESS = 'INITIAL_DATA_SUCCESS';

export const SAVE_EMPRESA_REQUEST = 'SAVE_EMPRESA_REQUEST';
export const SAVE_EMPRESA_SUCCESS = 'SAVE_EMPRESA_SUCCESS';

export const SAVE_CUENTA_REQUEST = 'SAVE_CUENTA_REQUEST';
export const SAVE_CUENTA_SUCCESS = 'SAVE_CUENTA_SUCCESS';

export const SAVE_INDICADOR_REQUEST = 'SAVE_INDICADOR_REQUEST';
export const SAVE_INDICADOR_SUCCESS = 'SAVE_INDICADOR_SUCCESS';

export const SAVE_METODOLOGIA_REQUEST = 'SAVE_METODOLOGIA_REQUEST';
export const SAVE_METODOLOGIA_SUCCESS = 'SAVE_METODOLOGIA_SUCCESS';
