package myfirstproject.rules
import edu.utn.frba.dds.grupo5.entidades.CuentaEmpresa;
import edu.utn.frba.dds.grupo5.entidades.Metodologia;
import edu.utn.frba.dds.grupo5.entidades.Empresa;

rule "Buffet2"
 when
 	$e: Metodologia(nombre == "p2") 
 then
 	System.out.println($e.getNombre());
end

rule "Buffet"
 when
 	$m: Metodologia(nombre == "Buffet")
 then
 	$m.minimizar("Deuda", 1);
 	$m.ordenarConsistencia("ROE", 10);
 	$m.consistencia("Margen",10);
 	$m.ordenarAntiguedad();
 	$m.aniosAntiguedad(10);
end

rule "p3"
 when
 	$e: Metodologia(nombre == "p3") 
 then
 	$e.maximizar("ROE", 1);
 	$e.aniosAntiguedad(10);
 	$e.minimizar("Deuda", 3);
 	$e.ordenarAntiguedad();
end

rule "p4"
 when
 	$e: Metodologia(nombre == "p4") 
 then
 	$e.aniosAntiguedad(10);
 	$e.consistencia("Margen",5);
 	$e.ordenarConsistencia("I2", 2);
end