package myfirstproject.rules
import edu.utn.frba.dds.grupo5.entidades.CuentaEmpresa;
import edu.utn.frba.dds.grupo5.entidades.Metodologia;
import edu.utn.frba.dds.grupo5.entidades.Empresa;

rule "Buffet"
 when
 	$m: Metodologia(nombre == "Buffet")
 then
 	$m.minimizar("Deuda", 1);
 	$m.ordenarConsistencia("ROE", 10);
 	$m.consistencia("Margen",10);
 	$m.ordenarAntiguedad();
 	$m.aniosAntiguedad(10);
end

rule "Debt"
 when
 	$e: Metodologia(nombre == "Debt") 
 then
 	$e.maximizar("ROE", 1);
 	$e.aniosAntiguedad(10);
 	$e.minimizar("Deuda", 3);
 	$e.ordenarAntiguedad();
end

rule "Constante"
 when
 	$e: Metodologia(nombre == "Constante") 
 then
 	$e.aniosAntiguedad(10);
 	$e.consistencia("Margen",5);
 	$e.ordenarConsistencia("I2", 2);
end

rule "LastYear"
 when
 	$c: Metodologia(nombre == "LastYear") 
 then
 	$c.aniosAntiguedad(10);
 	$c.maximizar("ROE", 1);
 	$c.maximizar("I2", 1);
 	$c.ordenarAntiguedad();
end

rule "Historial"
 when
 	$p: Metodologia(nombre == "Historial")
 then
 	$p.aniosAntiguedad(15);
 	$p.ordenarAntiguedad();
 	$p.consistencia("ROE",2);
 	$p.minimizar("Deuda",5);
 	$p.maximizar("Margen",2);
end